//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectClone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        public int BookId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> Days { get; set; }
        public string Total { get; set; }
        public Nullable<int> PayStatus { get; set; }
    }
}
